package com.cosm.olot.modKSL;

import android.util.Log;
import android.widget.ImageView;

import com.cosm.olot.R;

import java.util.Random;

public class RandCard {

    ImageView ii1, ii2, ii3, ii4, ii5, ii6, ii7, ii8, ii9, ii10, ii11, ii12;

    public RandCard(ImageView ii1, ImageView ii2, ImageView ii3, ImageView ii4, ImageView ii5, ImageView ii6, ImageView ii7, ImageView ii8, ImageView ii9, ImageView ii10, ImageView ii11, ImageView ii12) {
        this.ii1 = ii1;
        this.ii2 = ii2;
        this.ii3 = ii3;
        this.ii4 = ii4;
        this.ii5 = ii5;
        this.ii6 = ii6;
        this.ii7 = ii7;
        this.ii8 = ii8;
        this.ii9 = ii9;
        this.ii10 = ii10;
        this.ii11 = ii11;
        this.ii12 = ii12;
    }

    public void randomCard(){
        Random random = new Random();
        switch (random.nextInt(10)){
            case 0:
                ii1.setImageResource(R.drawable.b1);
                ii1.setTag(1);
                ii2.setImageResource(R.drawable.b2);
                ii2.setTag(2);
                ii3.setImageResource(R.drawable.b3);
                ii3.setTag(3);
                ii4.setImageResource(R.drawable.b4);
                ii4.setTag(4);
                ii5.setImageResource(R.drawable.b5);
                ii5.setTag(5);
                ii6.setImageResource(R.drawable.b6);
                ii6.setTag(6);
                ii7.setImageResource(R.drawable.b5);
                ii7.setTag(5);
                ii8.setImageResource(R.drawable.b6);
                ii8.setTag(6);
                ii9.setImageResource(R.drawable.b4);
                ii9.setTag(4);
                ii10.setImageResource(R.drawable.b3);
                ii10.setTag(3);
                ii11.setImageResource(R.drawable.b2);
                ii11.setTag(2);
                ii12.setImageResource(R.drawable.b1);
                ii12.setTag(1);
                Log.d("ttt","0000");

                break;
            case 1:

                ii1.setImageResource(R.drawable.b6);
                ii1.setTag(6);
                ii2.setImageResource(R.drawable.b5);
                ii2.setTag(5);
                ii3.setImageResource(R.drawable.b4);
                ii3.setTag(4);
                ii4.setImageResource(R.drawable.b3);
                ii4.setTag(3);
                ii5.setImageResource(R.drawable.b2);
                ii5.setTag(2);
                ii6.setImageResource(R.drawable.b1);
                ii6.setTag(1);
                ii7.setImageResource(R.drawable.b1);
                ii7.setTag(1);
                ii8.setImageResource(R.drawable.b2);
                ii8.setTag(2);
                ii9.setImageResource(R.drawable.b3);
                ii9.setTag(3);
                ii10.setImageResource(R.drawable.b4);
                ii10.setTag(4);
                ii11.setImageResource(R.drawable.b5);
                ii11.setTag(5);
                ii12.setImageResource(R.drawable.b6);
                ii12.setTag(6);
                Log.d("ttt","111");
                break;
            case 2:
                ii1.setImageResource(R.drawable.b5);
                ii1.setTag(5);
                ii2.setImageResource(R.drawable.b6);
                ii2.setTag(6);
                ii3.setImageResource(R.drawable.b3);
                ii3.setTag(3);
                ii4.setImageResource(R.drawable.b4);
                ii4.setTag(4);
                ii5.setImageResource(R.drawable.b1);
                ii5.setTag(1);
                ii6.setImageResource(R.drawable.b2);
                ii6.setTag(2);
                ii7.setImageResource(R.drawable.b1);
                ii7.setTag(1);
                ii8.setImageResource(R.drawable.b2);
                ii8.setTag(2);
                ii9.setImageResource(R.drawable.b3);
                ii9.setTag(3);
                ii10.setImageResource(R.drawable.b5);
                ii10.setTag(5);
                ii11.setImageResource(R.drawable.b4);
                ii11.setTag(4);
                ii12.setImageResource(R.drawable.b6);
                ii12.setTag(6);
                Log.d("ttt","222");
                break;
            case 3:
                ii1.setImageResource(R.drawable.b1);
                ii1.setTag(1);
                ii2.setImageResource(R.drawable.b6);
                ii2.setTag(6);
                ii3.setImageResource(R.drawable.b1);
                ii3.setTag(1);
                ii4.setImageResource(R.drawable.b3);
                ii4.setTag(3);
                ii5.setImageResource(R.drawable.b5);
                ii5.setTag(5);
                ii6.setImageResource(R.drawable.b2);
                ii6.setTag(2);
                ii7.setImageResource(R.drawable.b4);
                ii7.setTag(4);
                ii8.setImageResource(R.drawable.b5);
                ii8.setTag(5);
                ii9.setImageResource(R.drawable.b3);
                ii9.setTag(3);
                ii10.setImageResource(R.drawable.b2);
                ii10.setTag(2);
                ii11.setImageResource(R.drawable.b6);
                ii11.setTag(6);
                ii12.setImageResource(R.drawable.b4);
                ii12.setTag(4);
                Log.d("ttt","333");
                break;
            case 4:

                ii1.setImageResource(R.drawable.b4);
                ii1.setTag(4);
                ii2.setImageResource(R.drawable.b3);
                ii2.setTag(3);
                ii3.setImageResource(R.drawable.b6);
                ii3.setTag(6);
                ii4.setImageResource(R.drawable.b4);
                ii4.setTag(4);
                ii5.setImageResource(R.drawable.b6);
                ii5.setTag(6);
                ii6.setImageResource(R.drawable.b5);
                ii6.setTag(5);
                ii7.setImageResource(R.drawable.b1);
                ii7.setTag(1);
                ii8.setImageResource(R.drawable.b5);
                ii8.setTag(5);
                ii9.setImageResource(R.drawable.b2);
                ii9.setTag(2);
                ii10.setImageResource(R.drawable.b2);
                ii10.setTag(2);
                ii11.setImageResource(R.drawable.b1);
                ii11.setTag(1);
                ii12.setImageResource(R.drawable.b3);
                ii12.setTag(3);
                Log.d("ttt","444");
                break;
            case 5:
                ii1.setImageResource(R.drawable.b4);
                ii1.setTag(4);
                ii2.setImageResource(R.drawable.b2);
                ii2.setTag(2);
                ii3.setImageResource(R.drawable.b3);
                ii3.setTag(3);
                ii4.setImageResource(R.drawable.b4);
                ii4.setTag(4);
                ii5.setImageResource(R.drawable.b2);
                ii5.setTag(2);
                ii6.setImageResource(R.drawable.b6);
                ii6.setTag(6);
                ii7.setImageResource(R.drawable.b1);
                ii7.setTag(1);
                ii8.setImageResource(R.drawable.b5);
                ii8.setTag(5);
                ii9.setImageResource(R.drawable.b3);
                ii9.setTag(3);
                ii10.setImageResource(R.drawable.b6);
                ii10.setTag(6);
                ii11.setImageResource(R.drawable.b1);
                ii11.setTag(1);
                ii12.setImageResource(R.drawable.b5);
                ii12.setTag(5);
                Log.d("ttt","5555");
                break;
            case 6:
                ii1.setImageResource(R.drawable.b1);
                ii1.setTag(1);
                ii2.setImageResource(R.drawable.b6);
                ii2.setTag(6);
                ii3.setImageResource(R.drawable.b5);
                ii3.setTag(5);
                ii4.setImageResource(R.drawable.b2);
                ii4.setTag(2);
                ii5.setImageResource(R.drawable.b3);
                ii5.setTag(3);
                ii6.setImageResource(R.drawable.b5);
                ii6.setTag(5);
                ii7.setImageResource(R.drawable.b1);
                ii7.setTag(1);
                ii8.setImageResource(R.drawable.b6);
                ii8.setTag(6);
                ii9.setImageResource(R.drawable.b3);
                ii9.setTag(3);
                ii10.setImageResource(R.drawable.b4);
                ii10.setTag(4);
                ii11.setImageResource(R.drawable.b2);
                ii11.setTag(2);
                ii12.setImageResource(R.drawable.b4);
                ii12.setTag(4);
                Log.d("ttt","6666");
                break;
            case 7:
                ii1.setImageResource(R.drawable.b2);
                ii1.setTag(2);
                ii2.setImageResource(R.drawable.b3);
                ii2.setTag(3);
                ii3.setImageResource(R.drawable.b5);
                ii3.setTag(5);
                ii4.setImageResource(R.drawable.b1);
                ii4.setTag(1);
                ii5.setImageResource(R.drawable.b4);
                ii5.setTag(4);
                ii6.setImageResource(R.drawable.b6);
                ii6.setTag(6);
                ii7.setImageResource(R.drawable.b3);
                ii7.setTag(3);
                ii8.setImageResource(R.drawable.b5);
                ii8.setTag(5);
                ii9.setImageResource(R.drawable.b2);
                ii9.setTag(2);
                ii10.setImageResource(R.drawable.b1);
                ii10.setTag(1);
                ii11.setImageResource(R.drawable.b6);
                ii11.setTag(6);
                ii12.setImageResource(R.drawable.b4);
                ii12.setTag(4);
                Log.d("ttt","7777");
                break;
            case 8:
                ii1.setImageResource(R.drawable.b4);
                ii1.setTag(4);
                ii2.setImageResource(R.drawable.b5);
                ii2.setTag(5);
                ii3.setImageResource(R.drawable.b3);
                ii3.setTag(3);
                ii4.setImageResource(R.drawable.b6);
                ii4.setTag(6);
                ii5.setImageResource(R.drawable.b3);
                ii5.setTag(3);
                ii6.setImageResource(R.drawable.b5);
                ii6.setTag(5);
                ii7.setImageResource(R.drawable.b2);
                ii7.setTag(2);
                ii8.setImageResource(R.drawable.b6);
                ii8.setTag(6);
                ii9.setImageResource(R.drawable.b4);
                ii9.setTag(4);
                ii10.setImageResource(R.drawable.b1);
                ii10.setTag(1);
                ii11.setImageResource(R.drawable.b2);
                ii11.setTag(2);
                ii12.setImageResource(R.drawable.b1);
                ii12.setTag(1);
                Log.d("ttt","8888");
                break;
            case 9:
                ii1.setImageResource(R.drawable.b3);
                ii1.setTag(3);
                ii2.setImageResource(R.drawable.b6);
                ii2.setTag(6);
                ii3.setImageResource(R.drawable.b4);
                ii3.setTag(4);
                ii4.setImageResource(R.drawable.b1);
                ii4.setTag(1);
                ii5.setImageResource(R.drawable.b3);
                ii5.setTag(3);
                ii6.setImageResource(R.drawable.b5);
                ii6.setTag(5);
                ii7.setImageResource(R.drawable.b6);
                ii7.setTag(6);
                ii8.setImageResource(R.drawable.b4);
                ii8.setTag(4);
                ii9.setImageResource(R.drawable.b2);
                ii9.setTag(2);
                ii10.setImageResource(R.drawable.b5);
                ii10.setTag(5);
                ii11.setImageResource(R.drawable.b2);
                ii11.setTag(2);
                ii12.setImageResource(R.drawable.b1);
                ii12.setTag(1);
                Log.d("ttt","9999");
                break;
        }
    }
}
